# This file was generated by GoReleaser. DO NOT EDIT.
cask "md-present" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "19b20e1e8000ba33961bcd0c004fc7a4c5abfe2d4a1bb9215bbf344b27e8fc9f"
      url "https://github.com/timonwd/md-present/releases/download/#{version}/md-present_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "md-present"
  desc "Turn one Markdown file into a local browser presentation"
  homepage "https://github.com/timonwd/md-present"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md-present"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md-present"]
    end
  end

  # No zap stanza required

end
