# This file was generated by GoReleaser. DO NOT EDIT.
cask "md-present" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "e9d34b84b917534c11af29e23d58c75d05b6e84048c73b01b8ad022f15f8804f"
      url "https://github.com/timonwd/md-present/releases/download/#{version}/md-present_#{version}_Darwin_arm64.tar.gz"
    end
  end

  name "md-present"
  desc "Turn one Markdown file into a local browser presentation"
  homepage "https://github.com/timonwd/md-present"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md-present"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md-present"]
      launch_agent = File.expand_path("~/Library/LaunchAgents/com.timonwd.md-present.mcp.plist")
      if File.exist?(launch_agent)
        system_command "/bin/launchctl", args: ["kickstart", "-k", "gui/#{Process.uid}/com.timonwd.md-present.mcp"], must_succeed: false
      end
    end
  end

  # No zap stanza required

end
